# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-06 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('user', models.CharField(max_length=255)),
                ('repo', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'github_hook',
            },
        ),
    ]
